# github

git init

git commit -m "first commit"

git branch -M main

git remote add origin https://github.com/Abouelyatim/test1.git

git push -u origin main

## **General**
1- What's the difference between a Machine Learning (ML) Model and a Machine Learning algorithm.

2- Why we need to study Linear Algebra for ML?

# Responses:
1-models are output by algorithms and are comprised of model data and a prediction algorithm.have bias and limit

algorithme help model to find parameters,

2-because  the base of ML is mathematique in particular linear algebra so to undrstand deeply we must know linear algebra
ex
matrix :we represente our data in format of matrix
vectors

**## Vectors:**

**1- create a vector: **

Our vector can be written as v=(2,1), but more formally we would use the following notation, in which the dimensional coordinate values for the vector are shown as a matrix:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$

In [1]:
import numpy as np
#TO DO...
v = np.array([2, 1])

print(v)

[2 1]


### **2-Calculating Magnitude**

In [3]:
import math
#TO DO... 
magnitude = np.linalg.norm(v)
print(magnitude)

2.23606797749979



**3- Vector Addition:**
So far, we've worked with one vector at a time. What happens when you need to add two vectors.

Let's take a look at an example, we already have a vector named v, as defined here:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$Now let's create a second vector, and called s like this:$$\vec{s} = \begin{bmatrix}-3 \\ 2 \end{bmatrix}$$

And we have :$$\vec{z} = \vec{v}+\vec{s}$$

In [6]:

import math
import numpy as np

v = np.array([2, 1])
s = np.array([-3, 2])
z =v+s
print (z)

[-1  3]



4- Dot Product Multiplication


$$ \vec{d}=\vec{v} \cdot \vec{s} = (v_{1} \cdot s_{1}) + (v_{2} \cdot s_{2}) ... + \; (v_{n} \cdot s_{n})$$

In [7]:

import math
import numpy as np

v = np.array([2, 1])
s = np.array([-3, 2])
d = np.dot(v,s)
print (d)

-4


## **Matrices:**

# 1- create a Matrice:
A matrix arranges numbers into rows and columns, like this:

$$A = \begin{bmatrix}
  1 &amp; 2 &amp; 3 \\
  4 &amp; 5 &amp; 6
 \end{bmatrix}
$$

In [9]:
import numpy as np

A = np.array([[1, 2,3],
              [4,5,6]])
print (A)

[[1 2 3]
 [4 5 6]]



#2- Matrix Transposition
You can transpose a matrix, that is switch the orientation of its rows and columns. You indicate this with a superscript T, like this:

$$\begin{bmatrix}1 &amp; 2 &amp; 3 \\4 &amp; 5 &amp; 6\end{bmatrix}^{T} = \begin{bmatrix}1 &amp; 42 &amp; 53 &amp; 6 \end{bmatrix}$$

a- How can we do it mathematically? 

first row will be the first column,after, second row second column ... until n row will be n column

For A in Rm*n the matrix B in Rn*m with
bij = aji is  transpose of A. 
 B = A t



b- with Python: 

In [10]:
import numpy as np

A= A.transpose()
print (A)

[[1 4]
 [2 5]
 [3 6]]


## **Eigendecomposition:**

So we've learned a little about eigenvalues and eigenvectors; but you may be wondering what use they are. Well, one use for them is to help decompose transformation matrices.

1- How can we decompose a matrix? ( Rules and steps)
2- (Bonus) Do it in python with your exampls.

1-........................................

In [ ]:
#2 bonus
import numpy as np